
# Configuracion MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/carhistorial?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=javier_admin
spring.datasource.password=MiNeClaSeRo1!CarHistorialBBDD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Configuración de seguridad crítica de tu JWT (Sustituye por tu clave real o una frase larga)
jwt.secret=EsEstaFraseSeDaAEntenderLoGranInbecilQueSoyPorPonerEstaFraseLaVerdadQueMeGustoMuchoEsteProyectoGustaaa
# Expiración del token (24 horas en milisegundos)
jwt.expiration=86400000